---
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  Test::Pod: 1.41
  Test::Pod::Coverage: 1.08
  Test::UseAllModules: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PagSeguro
no_index:
  directory:
    - inc
    - t
requires:
  HTML::Zoom: 0
  Moose: 0
  MooseX::Types::Email: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
